# site settings
title: "JKU GAMES 2022W"
subtitle: "JKU Linz, Uni-Center, 04. bis 06. November"
email: "games@oeh.jku.at"
description: "04.11. 16:00 - 38h<br> > Powered by <br><a class='img' href='https://liwest.bewerberportal.at/Jobs'><img src='/assets/images/Sponsoring Logos JKU Games 2022W Liwest.png' style='max-width: 200px; padding: 0px;' alt='Sponsor LIWEST' /></a>"
baseurl: "" 
url: "https://games.oeh.jku.at/"
author: JKU Games Team
street_address: "JKU Linz, Uni-Center<br>Altenbergerstraße 69"
city: Linz
state: AT
zip_code: 4040
country: Österreich
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: 
facebook_url: "https://facebook.com/jkugames"
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: "https://instagram.com/oehtnf"
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
discord_url: "https://discord.gg/46Hg8v57s9"

# build settings
markdown: kramdown

sass:
  style: compressed
