# site settings
title: "JKU GAMES 2022"
subtitle: "JKU Linz, Bankengebäude, 29.04. - 01.05."
email: "games@oeh.jku.at"
description: "JKU Linz, Bankengebäude, 29.04. - 01.05."
baseurl: "/" 
url: "https://games.oeh.jku.at/"
author: JKU Games Team
street_address: "JKU Linz, Bankengebäude, <br>Altenbergerstraße 69"
city: Linz
state: AT
zip_code: 4040
country: Österreich
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: 
facebook_url: "https://facebook.com/jkugames"
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: "https://instagram.com/oehtnf"
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
