# site settings
title: "JKU GAMES 2023S"
subtitle: "JKU Linz, Uni-Center, 17. - 19.03."
email: "games@oeh.jku.at"
description: "17.03. 16:00 - 19.03. 06:00"
baseurl: "" 
url: "https://games.oeh.jku.at/"
author: JKU Games Team
street_address: "JKU Linz, Uni-Center<br>Altenbergerstraße 69"
city: Linz
state: AT
zip_code: 4040
country: Österreich
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url: 
facebook_url: "https://facebook.com/jkugames"
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: "https://instagram.com/oehtnf"
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
discord_url: "https://discord.gg/46Hg8v57s9"

# build settings
markdown: kramdown

sass:
  style: compressed
